-- HRM/BPM optional-module baseline for MySQL 8.0+.
-- Apply after sql/mysql/ruoyi-vue-pro.sql and before starting a -Phrm build.
-- Additive, repeatable table creation only; no DROP, salary data or policy defaults.
-- Existing tables are not altered: compare their columns before applying to an
-- installation that already has HRM/BPM. Flowable manages its own engine schema.
-- TEXT columns store the serialized values consumed by existing type handlers.

CREATE TABLE IF NOT EXISTS `hrm_employee` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `job_number` varchar(64) DEFAULT NULL,
    `user_id` bigint DEFAULT NULL,
    `mobile` varchar(255) DEFAULT NULL,
    `country` varchar(64) DEFAULT NULL,
    `nation` varchar(64) DEFAULT NULL,
    `id_type` tinyint DEFAULT NULL,
    `id_number` varchar(255) DEFAULT NULL,
    `sex` tinyint DEFAULT NULL,
    `email` varchar(255) DEFAULT NULL,
    `native_place` varchar(128) DEFAULT NULL,
    `birthday` datetime DEFAULT NULL,
    `age` int DEFAULT NULL,
    `address` varchar(255) DEFAULT NULL,
    `highest_education` tinyint DEFAULT NULL,
    `dept_id` bigint DEFAULT NULL,
    `leader_employee_id` bigint DEFAULT NULL,
    `entry_status` tinyint DEFAULT NULL,
    `status` tinyint DEFAULT NULL,
    `type` tinyint DEFAULT NULL,
    `entry_time` datetime DEFAULT NULL,
    `probation` int DEFAULT NULL,
    `regular_time` datetime DEFAULT NULL,
    `leave_time` datetime DEFAULT NULL,
    `post_name` varchar(255) DEFAULT NULL,
    `post_level` varchar(255) DEFAULT NULL,
    `work_city` varchar(64) DEFAULT NULL,
    `work_address` varchar(255) DEFAULT NULL,
    `work_detail_address` varchar(255) DEFAULT NULL,
    `channel_id` bigint DEFAULT NULL,
    `company_age_start_time` datetime DEFAULT NULL,
    `company_age` int DEFAULT NULL,
    `candidate_id` bigint DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_job_number` (`tenant_id`, `job_number`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_employee_education_experience` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `education` tinyint DEFAULT NULL,
    `graduate_school` varchar(255) DEFAULT NULL,
    `major` varchar(255) DEFAULT NULL,
    `admission_time` datetime DEFAULT NULL,
    `graduation_time` datetime DEFAULT NULL,
    `teaching_methods` tinyint DEFAULT NULL,
    `first_degree` bit(1) DEFAULT NULL,
    `sort` int DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_employee_work_experience` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `work_unit` varchar(255) DEFAULT NULL,
    `post_name` varchar(255) DEFAULT NULL,
    `start_time` datetime DEFAULT NULL,
    `end_time` datetime DEFAULT NULL,
    `reason` text DEFAULT NULL,
    `witness_name` varchar(255) DEFAULT NULL,
    `witness_phone` varchar(32) DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `sort` int DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_employee_training_experience` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `course` varchar(128) DEFAULT NULL,
    `organization_name` varchar(128) DEFAULT NULL,
    `start_time` datetime DEFAULT NULL,
    `end_time` datetime DEFAULT NULL,
    `duration` varchar(64) DEFAULT NULL,
    `result` varchar(64) DEFAULT NULL,
    `certificate_name` varchar(128) DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `sort` int DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_employee_certificate` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `name` varchar(255) DEFAULT NULL,
    `level` varchar(255) DEFAULT NULL,
    `no` varchar(255) DEFAULT NULL,
    `start_time` datetime DEFAULT NULL,
    `end_time` datetime DEFAULT NULL,
    `issuing_authority` varchar(255) DEFAULT NULL,
    `issuing_time` datetime DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `sort` int DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_employee_contact` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `name` varchar(64) DEFAULT NULL,
    `relation` varchar(64) DEFAULT NULL,
    `phone` varchar(40) DEFAULT NULL,
    `work_unit` varchar(128) DEFAULT NULL,
    `post_name` varchar(128) DEFAULT NULL,
    `address` varchar(255) DEFAULT NULL,
    `sort` int DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_employee_contract` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `no` varchar(128) DEFAULT NULL,
    `type` tinyint DEFAULT NULL,
    `start_time` datetime DEFAULT NULL,
    `end_time` datetime DEFAULT NULL,
    `term` int DEFAULT NULL,
    `status` tinyint DEFAULT NULL,
    `sign_company` varchar(255) DEFAULT NULL,
    `sign_time` datetime DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `expire_remind` bit(1) DEFAULT NULL,
    `sort` int DEFAULT NULL,
    `file_urls` text DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_employee_file` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `type` tinyint NOT NULL,
    `url` varchar(512) NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_employee_change_record` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `type` tinyint DEFAULT NULL,
    `reason` tinyint DEFAULT NULL,
    `old_dept_id` bigint DEFAULT NULL,
    `new_dept_id` bigint DEFAULT NULL,
    `old_post_name` varchar(255) DEFAULT NULL,
    `new_post_name` varchar(255) DEFAULT NULL,
    `old_post_level` varchar(255) DEFAULT NULL,
    `new_post_level` varchar(255) DEFAULT NULL,
    `old_work_address` varchar(255) DEFAULT NULL,
    `new_work_address` varchar(255) DEFAULT NULL,
    `old_leader_employee_id` bigint DEFAULT NULL,
    `new_leader_employee_id` bigint DEFAULT NULL,
    `probation` int DEFAULT NULL,
    `effect_time` datetime DEFAULT NULL,
    `applied_time` datetime DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_employee_quit_info` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `plan_quit_time` datetime DEFAULT NULL,
    `apply_quit_time` datetime DEFAULT NULL,
    `salary_settlement_time` datetime DEFAULT NULL,
    `type` tinyint DEFAULT NULL,
    `reason` tinyint DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `old_employee_status` tinyint DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_attendance_leave` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `type` varchar(64) DEFAULT NULL,
    `start_time` datetime DEFAULT NULL,
    `end_time` datetime DEFAULT NULL,
    `day` decimal(10, 2) DEFAULT NULL,
    `reason` varchar(300) DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `approval_status` tinyint NOT NULL,
    `process_instance_id` varchar(64) DEFAULT NULL,
    `approval_time` datetime DEFAULT NULL,
    `approval_reason` varchar(500) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    CONSTRAINT `uk_hrm_attendance_leave_process_instance_id` UNIQUE (`process_instance_id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`),
    KEY `idx_process_instance_id` (`tenant_id`, `process_instance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_config` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `type` tinyint NOT NULL,
    `value` varchar(255) NOT NULL,
    `sort` int DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_employee_personal_note` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `content` text NOT NULL,
    `reminder_time` datetime NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_recruit_post_type` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(40) DEFAULT NULL,
    `parent_id` bigint DEFAULT NULL,
    `sort` int DEFAULT NULL,
    `status` tinyint DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_recruit_channel` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `system_flag` bit(1) DEFAULT b'0',
    `status` tinyint DEFAULT NULL,
    `name` varchar(255) NOT NULL,
    `sort` int DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_recruit_post` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `post_name` varchar(255) NOT NULL,
    `dept_id` bigint DEFAULT NULL,
    `job_nature` tinyint DEFAULT NULL,
    `area_id` int DEFAULT NULL,
    `recruit_num` int DEFAULT NULL,
    `reason` varchar(255) DEFAULT NULL,
    `work_time` tinyint DEFAULT NULL,
    `education_require` tinyint DEFAULT NULL,
    `min_salary` decimal(10, 2) DEFAULT NULL,
    `max_salary` decimal(10, 2) DEFAULT NULL,
    `salary_unit` tinyint DEFAULT NULL,
    `min_age` int DEFAULT NULL,
    `max_age` int DEFAULT NULL,
    `latest_entry_time` datetime DEFAULT NULL,
    `owner_employee_id` bigint DEFAULT NULL,
    `interview_employee_ids` varchar(255) DEFAULT NULL,
    `description` text DEFAULT NULL,
    `emergency_level` tinyint DEFAULT NULL,
    `post_type_id` bigint DEFAULT NULL,
    `status` tinyint DEFAULT NULL,
    `stop_reason` varchar(255) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_recruit_candidate` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `mobile` varchar(255) NOT NULL,
    `sex` tinyint NOT NULL,
    `age` int DEFAULT NULL,
    `email` varchar(255) DEFAULT NULL,
    `post_id` bigint NOT NULL,
    `stage_number` int DEFAULT NULL,
    `work_time` int DEFAULT NULL,
    `education` tinyint NOT NULL,
    `graduate_school` varchar(255) DEFAULT NULL,
    `latest_work_place` varchar(255) DEFAULT NULL,
    `channel_id` bigint DEFAULT NULL,
    `remark` varchar(255) DEFAULT NULL,
    `status` tinyint DEFAULT NULL,
    `eliminate` varchar(255) DEFAULT NULL,
    `status_update_time` datetime DEFAULT NULL,
    `entry_time` datetime DEFAULT NULL,
    `resume_urls` text DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_recruit_interview` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `candidate_id` bigint NOT NULL,
    `type` tinyint DEFAULT NULL,
    `stage_number` int DEFAULT NULL,
    `interview_employee_id` bigint DEFAULT NULL,
    `other_interview_employee_ids` varchar(255) DEFAULT NULL,
    `interview_time` datetime DEFAULT NULL,
    `address` varchar(255) DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `result` tinyint DEFAULT NULL,
    `evaluate` varchar(255) DEFAULT NULL,
    `cancel_reason` varchar(255) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_attendance_group` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(50) NOT NULL,
    `dept_ids` text DEFAULT NULL,
    `employee_ids` text DEFAULT NULL,
    `open_wifi_card` bit(1) NOT NULL DEFAULT b'0',
    `open_point_card` bit(1) NOT NULL DEFAULT b'0',
    `shifts` text NOT NULL,
    `rest` bit(1) NOT NULL DEFAULT b'1',
    `special_dates` text NOT NULL,
    `points` text NOT NULL,
    `wifis` text NOT NULL,
    `deduct_rule` text NOT NULL,
    `default_status` bit(1) NOT NULL DEFAULT b'0',
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_attendance_holiday` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `date` datetime NOT NULL,
    `type` tinyint DEFAULT 2,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_attendance_clock` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint DEFAULT NULL,
    `clock_time` datetime NOT NULL,
    `type` tinyint NOT NULL,
    `attendance_time` datetime NOT NULL,
    `source_type` tinyint DEFAULT 2,
    `status` tinyint DEFAULT 0,
    `stage` int DEFAULT 1,
    `address` varchar(255) DEFAULT NULL,
    `longitude` decimal(10, 6) DEFAULT NULL,
    `latitude` decimal(10, 6) DEFAULT NULL,
    `ssid` varchar(50) DEFAULT NULL,
    `mac` varchar(50) DEFAULT NULL,
    `remark` varchar(255) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_salary_config` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `cycle_start_day` int DEFAULT NULL,
    `cycle_end_day` int DEFAULT NULL,
    `social_security_month_type` tinyint DEFAULT NULL,
    `start_year` int DEFAULT NULL,
    `start_month` int DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    CONSTRAINT `uk_hrm_salary_config_tenant_id` UNIQUE (`tenant_id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_salary_tax_rule` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(64) NOT NULL,
    `type` tinyint DEFAULT NULL,
    `tax_enabled` bit(1) DEFAULT NULL,
    `threshold` decimal(12, 2) DEFAULT NULL,
    `decimal_scale` int DEFAULT NULL,
    `cycle_type` tinyint DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_salary_group` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(64) NOT NULL,
    `salary_standard` decimal(12, 2) DEFAULT NULL,
    `change_rule` varchar(255) DEFAULT NULL,
    `dept_ids` mediumtext DEFAULT NULL,
    `employee_ids` mediumtext DEFAULT NULL,
    `tax_rule_id` bigint DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_salary_option_template` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `code` int NOT NULL,
    `parent_code` int NOT NULL DEFAULT 0,
    `name` varchar(64) NOT NULL,
    `remark` varchar(255) DEFAULT NULL,
    `system_flag` bit(1) NOT NULL DEFAULT b'0',
    `type` tinyint NOT NULL DEFAULT 1,
    `tax_enabled` bit(1) NOT NULL DEFAULT b'1',
    `visible` bit(1) NOT NULL DEFAULT b'1',
    `calculate_enabled` bit(1) NOT NULL DEFAULT b'1',
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    PRIMARY KEY (`id`),
    CONSTRAINT `uk_hrm_salary_option_template_code` UNIQUE (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_salary_option` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `code` int NOT NULL,
    `parent_code` int NOT NULL DEFAULT 0,
    `name` varchar(64) NOT NULL,
    `remark` varchar(255) DEFAULT NULL,
    `system_flag` bit(1) NOT NULL DEFAULT b'0',
    `template_id` bigint DEFAULT NULL,
    `type` tinyint NOT NULL DEFAULT 1,
    `tax_enabled` bit(1) NOT NULL DEFAULT b'1',
    `visible` bit(1) NOT NULL DEFAULT b'1',
    `calculate_enabled` bit(1) NOT NULL DEFAULT b'1',
    `enabled` bit(1) NOT NULL DEFAULT b'1',
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    CONSTRAINT `uk_hrm_salary_option_tenant_code` UNIQUE (`tenant_id`, `code`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_salary_employee_info` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `change_reason` tinyint DEFAULT NULL,
    `effect_time` datetime DEFAULT NULL,
    `change_type` tinyint DEFAULT NULL,
    `probation_salary` decimal(12, 2) DEFAULT NULL,
    `regular_salary` decimal(12, 2) DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `salary_options` mediumtext DEFAULT NULL,
    `probation_salary_options` mediumtext DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    CONSTRAINT `uk_hrm_salary_employee_info_employee_id` UNIQUE (`employee_id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_salary_change_record` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `type` tinyint DEFAULT NULL,
    `reason` tinyint DEFAULT NULL,
    `effect_time` datetime DEFAULT NULL,
    `before_total` decimal(12, 2) DEFAULT NULL,
    `after_total` decimal(12, 2) DEFAULT NULL,
    `probation_before_total` decimal(12, 2) DEFAULT NULL,
    `probation_after_total` decimal(12, 2) DEFAULT NULL,
    `salary_options` text DEFAULT NULL,
    `probation_salary_options` text DEFAULT NULL,
    `status` tinyint DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_salary_change_template` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(64) NOT NULL,
    `default_status` bit(1) NOT NULL DEFAULT b'0',
    `options` text DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_salary_month_record` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `title` varchar(128) DEFAULT NULL,
    `year` int NOT NULL,
    `month` int NOT NULL,
    `employee_count` int DEFAULT NULL,
    `start_time` datetime DEFAULT NULL,
    `end_time` datetime DEFAULT NULL,
    `expected_pay_salary` decimal(12, 2) DEFAULT NULL,
    `personal_tax` decimal(12, 2) DEFAULT NULL,
    `real_pay_salary` decimal(12, 2) DEFAULT NULL,
    `personal_insurance_amount` decimal(12, 2) DEFAULT NULL,
    `personal_provident_fund_amount` decimal(12, 2) DEFAULT NULL,
    `corporate_insurance_amount` decimal(12, 2) DEFAULT NULL,
    `corporate_provident_fund_amount` decimal(12, 2) DEFAULT NULL,
    `option_headers` mediumtext DEFAULT NULL,
    `status` tinyint DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_year_month` (`tenant_id`, `year`, `month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_salary_month_employee_record` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `month_record_id` bigint NOT NULL,
    `employee_id` bigint NOT NULL,
    `actual_work_day` decimal(10, 2) DEFAULT NULL,
    `need_work_day` decimal(10, 2) DEFAULT NULL,
    `year` int NOT NULL,
    `month` int NOT NULL,
    `expected_pay_salary` decimal(12, 2) DEFAULT NULL,
    `taxable_salary` decimal(12, 2) DEFAULT NULL,
    `personal_tax` decimal(12, 2) DEFAULT NULL,
    `real_pay_salary` decimal(12, 2) DEFAULT NULL,
    `option_values` mediumtext DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`),
    KEY `idx_year_month` (`tenant_id`, `year`, `month`),
    KEY `idx_month_record_id` (`tenant_id`, `month_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_salary_slip_template` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(64) NOT NULL,
    `hide_empty` bit(1) NOT NULL DEFAULT b'0',
    `default_status` bit(1) NOT NULL DEFAULT b'0',
    `options` mediumtext NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_salary_slip_send_record` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `month_record_id` bigint NOT NULL,
    `employee_count` int DEFAULT NULL,
    `send_employee_count` int DEFAULT NULL,
    `year` int NOT NULL,
    `month` int NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_year_month` (`tenant_id`, `year`, `month`),
    KEY `idx_month_record_id` (`tenant_id`, `month_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_salary_slip` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `send_record_id` bigint NOT NULL,
    `month_employee_record_id` bigint NOT NULL,
    `employee_id` bigint NOT NULL,
    `year` int NOT NULL,
    `month` int NOT NULL,
    `read_status` tinyint DEFAULT NULL,
    `real_pay_salary` decimal(12, 2) DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `options` mediumtext NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`),
    KEY `idx_year_month` (`tenant_id`, `year`, `month`),
    KEY `idx_send_record_id` (`tenant_id`, `send_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_insurance_scheme` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(64) NOT NULL,
    `area_id` int DEFAULT NULL,
    `household_type` varchar(64) DEFAULT NULL,
    `type` tinyint NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_insurance_scheme_project` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `scheme_id` bigint NOT NULL,
    `type` tinyint NOT NULL,
    `name` varchar(64) NOT NULL,
    `base_amount` decimal(12, 2) DEFAULT NULL,
    `corporate_rate` decimal(10, 2) DEFAULT NULL,
    `personal_rate` decimal(10, 2) DEFAULT NULL,
    `corporate_amount` decimal(12, 2) DEFAULT NULL,
    `personal_amount` decimal(12, 2) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_insurance_employee_info` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `first_social_security` bit(1) NOT NULL DEFAULT b'0',
    `first_accumulation_fund` bit(1) NOT NULL DEFAULT b'0',
    `social_security_number` varchar(64) DEFAULT NULL,
    `accumulation_fund_number` varchar(64) DEFAULT NULL,
    `social_security_start_month` datetime DEFAULT NULL,
    `scheme_id` bigint DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_employee_salary_card` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `employee_id` bigint NOT NULL,
    `bank_card_number` varchar(64) DEFAULT NULL,
    `bank_area_id` int DEFAULT NULL,
    `bank_name` varchar(64) DEFAULT NULL,
    `bank_branch_name` varchar(128) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_insurance_month_record` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `title` varchar(128) DEFAULT NULL,
    `year` int NOT NULL,
    `month` int NOT NULL,
    `insured_employee_count` int DEFAULT NULL,
    `stopped_employee_count` int DEFAULT NULL,
    `status` tinyint DEFAULT NULL,
    `personal_insurance_amount` decimal(12, 2) DEFAULT NULL,
    `personal_provident_fund_amount` decimal(12, 2) DEFAULT NULL,
    `corporate_insurance_amount` decimal(12, 2) DEFAULT NULL,
    `corporate_provident_fund_amount` decimal(12, 2) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_year_month` (`tenant_id`, `year`, `month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_insurance_month_employee_record` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `month_record_id` bigint NOT NULL,
    `employee_id` bigint NOT NULL,
    `scheme_id` bigint DEFAULT NULL,
    `year` int NOT NULL,
    `month` int NOT NULL,
    `personal_insurance_amount` decimal(12, 2) DEFAULT NULL,
    `personal_provident_fund_amount` decimal(12, 2) DEFAULT NULL,
    `corporate_insurance_amount` decimal(12, 2) DEFAULT NULL,
    `corporate_provident_fund_amount` decimal(12, 2) DEFAULT NULL,
    `status` tinyint DEFAULT NULL,
    `projects` text NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`),
    KEY `idx_year_month` (`tenant_id`, `year`, `month`),
    KEY `idx_month_record_id` (`tenant_id`, `month_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_template` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(500) NOT NULL,
    `illustrate` varchar(1000) DEFAULT NULL,
    `score_calculation` tinyint DEFAULT 1,
    `upper_limit_type` tinyint DEFAULT 0,
    `upper_limit_score` decimal(10, 2) DEFAULT 100.00,
    `dimension_count` int DEFAULT 0,
    `quota_count` int DEFAULT 0,
    `dimensions` mediumtext NOT NULL,
    `status` tinyint DEFAULT 0,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_performance_result_template` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `levels` mediumtext NOT NULL,
    `status` tinyint DEFAULT 0,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_performance_plan` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `cycle_type` tinyint DEFAULT NULL,
    `cycle` varchar(255) DEFAULT NULL,
    `quarter` tinyint DEFAULT NULL,
    `start_time` datetime DEFAULT NULL,
    `end_time` datetime DEFAULT NULL,
    `description` varchar(1000) DEFAULT NULL,
    `scopes` mediumtext NOT NULL,
    `assessment_template_id` bigint NOT NULL,
    `assessment_config` mediumtext NOT NULL,
    `result_template_id` bigint NOT NULL,
    `result_config` mediumtext NOT NULL,
    `quota_setting_type` tinyint NOT NULL DEFAULT 1,
    `target_confirmation` bit(1) DEFAULT b'0' NOT NULL,
    `target_confirmation_stage` mediumtext DEFAULT NULL,
    `review_stages` mediumtext NOT NULL,
    `result_audit` bit(1) DEFAULT b'1' NOT NULL,
    `result_audit_stages` mediumtext DEFAULT NULL,
    `result_confirmation` bit(1) DEFAULT b'1' NOT NULL,
    `appeal_stages` mediumtext DEFAULT NULL,
    `appeal_timeout_days` int DEFAULT 2 NOT NULL,
    `appeal_timeout_action` tinyint DEFAULT 1 NOT NULL,
    `sync_to_salary` bit(1) DEFAULT b'0',
    `paid_for_month` varchar(20) DEFAULT NULL,
    `stage_type` tinyint DEFAULT 0,
    `status` tinyint DEFAULT 2,
    `operation_type` tinyint DEFAULT NULL,
    `terminate_time` datetime DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_performance_assessment` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `plan_id` bigint NOT NULL,
    `employee_id` bigint NOT NULL,
    `status` tinyint DEFAULT 2,
    `process_status` tinyint DEFAULT 1,
    `stage_type` tinyint DEFAULT 0,
    `stage_sort` int DEFAULT 0,
    `score` decimal(10, 2) DEFAULT 0.00,
    `result_level` varchar(64) DEFAULT NULL,
    `coefficient` decimal(10, 2) DEFAULT 1.00,
    `target_confirmation_result` tinyint DEFAULT NULL,
    `target_confirmation_comment` varchar(1000) DEFAULT NULL,
    `target_confirmation_time` datetime DEFAULT NULL,
    `self_comment` text DEFAULT NULL,
    `reviewer_comment` text DEFAULT NULL,
    `result_comment` text DEFAULT NULL,
    `result_confirmation_time` datetime DEFAULT NULL,
    `result_audit_status` tinyint DEFAULT NULL,
    `result_audit_time` datetime DEFAULT NULL,
    `result_audit_reason` varchar(1000) DEFAULT NULL,
    `appeal_reason` varchar(1000) DEFAULT NULL,
    `appeal_file_urls` text DEFAULT NULL,
    `appeal_submit_time` datetime DEFAULT NULL,
    `appeal_status` tinyint DEFAULT 0,
    `appeal_time` datetime DEFAULT NULL,
    `appeal_comment` varchar(1000) DEFAULT NULL,
    `archive_time` datetime DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`),
    KEY `idx_plan_id` (`tenant_id`, `plan_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_appeal_record` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `assessment_id` bigint NOT NULL,
    `stage_id` bigint NOT NULL,
    `status` tinyint NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_assessment_id` (`tenant_id`, `assessment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_action_record` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `assessment_id` bigint NOT NULL,
    `stage_id` bigint DEFAULT NULL,
    `employee_id` bigint DEFAULT NULL,
    `type` tinyint NOT NULL,
    `title` varchar(128) NOT NULL,
    `content` text DEFAULT NULL,
    `file_urls` text DEFAULT NULL,
    `status` tinyint DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_employee_id` (`tenant_id`, `employee_id`),
    KEY `idx_assessment_id` (`tenant_id`, `assessment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_stage` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `assessment_id` bigint NOT NULL,
    `type` tinyint NOT NULL,
    `name` varchar(128) NOT NULL,
    `handler_employee_id` bigint DEFAULT NULL,
    `rater_type` tinyint DEFAULT NULL,
    `weight` decimal(10, 2) DEFAULT NULL,
    `scoring_type` tinyint DEFAULT NULL,
    `visible_content` tinyint DEFAULT NULL,
    `required_setting` bit(1) DEFAULT NULL,
    `reject_authority` bit(1) DEFAULT NULL,
    `sort` int NOT NULL DEFAULT 0,
    `status` tinyint NOT NULL DEFAULT 0,
    `score` decimal(10, 2) DEFAULT NULL,
    `result_level` varchar(64) DEFAULT NULL,
    `comment` text DEFAULT NULL,
    `reject_reason` varchar(1000) DEFAULT NULL,
    `submit_time` datetime DEFAULT NULL,
    `deadline_time` datetime DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_assessment_id` (`tenant_id`, `assessment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_quota_score` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `assessment_stage_id` bigint NOT NULL,
    `assessment_quota_id` bigint NOT NULL,
    `score` decimal(10, 2) NOT NULL,
    `comment` varchar(1000) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_dimension` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `assessment_id` bigint NOT NULL,
    `name` varchar(255) NOT NULL,
    `quota_type` tinyint DEFAULT NULL,
    `weight` decimal(10, 2) DEFAULT NULL,
    `remark` varchar(255) DEFAULT NULL,
    `allow_edit` bit(1) NOT NULL DEFAULT b'0',
    `sort` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_assessment_id` (`tenant_id`, `assessment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_performance_assessment_quota` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `assessment_id` bigint NOT NULL,
    `dimension_id` bigint NOT NULL,
    `preset` bit(1) NOT NULL DEFAULT b'1',
    `name` varchar(255) DEFAULT NULL,
    `description` varchar(1000) DEFAULT NULL,
    `standard` varchar(1000) DEFAULT NULL,
    `weight` decimal(10, 2) DEFAULT 100.00,
    `score_type` tinyint DEFAULT NULL,
    `target_value` varchar(1000) DEFAULT NULL,
    `actual_value` varchar(1000) DEFAULT NULL,
    `self_score` decimal(10, 2) DEFAULT 0.00,
    `reviewer_score` decimal(10, 2) DEFAULT 0.00,
    `final_score` decimal(10, 2) DEFAULT 0.00,
    `sort` int DEFAULT 0,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_assessment_id` (`tenant_id`, `assessment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- BPM application tables (distinct from ACT_* / FLW_* engine tables).

CREATE TABLE IF NOT EXISTS `bpm_category` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(255) DEFAULT NULL,
    `code` varchar(64) DEFAULT NULL,
    `description` text DEFAULT NULL,
    `status` int DEFAULT NULL,
    `sort` int DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bpm_form` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(255) DEFAULT NULL,
    `status` int DEFAULT NULL,
    `conf` mediumtext DEFAULT NULL,
    `fields` mediumtext DEFAULT NULL,
    `remark` text DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bpm_process_definition_info` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `process_definition_id` varchar(64) DEFAULT NULL,
    `model_id` varchar(64) DEFAULT NULL,
    `model_type` int DEFAULT NULL,
    `category` varchar(64) DEFAULT NULL,
    `icon` varchar(255) DEFAULT NULL,
    `description` text DEFAULT NULL,
    `form_type` int DEFAULT NULL,
    `form_id` bigint DEFAULT NULL,
    `form_conf` mediumtext DEFAULT NULL,
    `form_fields` mediumtext DEFAULT NULL,
    `form_custom_create_path` varchar(255) DEFAULT NULL,
    `form_custom_view_path` varchar(255) DEFAULT NULL,
    `simple_model` mediumtext DEFAULT NULL,
    `visible` bit(1) DEFAULT NULL,
    `sort` bigint DEFAULT NULL,
    `start_user_ids` text DEFAULT NULL,
    `start_dept_ids` text DEFAULT NULL,
    `manager_user_ids` text DEFAULT NULL,
    `allow_cancel_running_process` bit(1) DEFAULT NULL,
    `allow_withdraw_task` bit(1) DEFAULT NULL,
    `process_id_rule` mediumtext DEFAULT NULL,
    `auto_approval_type` int DEFAULT NULL,
    `title_setting` mediumtext DEFAULT NULL,
    `summary_setting` mediumtext DEFAULT NULL,
    `process_before_trigger_setting` mediumtext DEFAULT NULL,
    `process_after_trigger_setting` mediumtext DEFAULT NULL,
    `task_before_trigger_setting` mediumtext DEFAULT NULL,
    `task_after_trigger_setting` mediumtext DEFAULT NULL,
    `print_template_setting` mediumtext DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_process_definition_id` (`tenant_id`, `process_definition_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bpm_process_expression` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(255) DEFAULT NULL,
    `status` int DEFAULT NULL,
    `expression` text DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bpm_process_listener` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(255) DEFAULT NULL,
    `status` int DEFAULT NULL,
    `type` varchar(64) DEFAULT NULL,
    `event` varchar(64) DEFAULT NULL,
    `value_type` varchar(64) DEFAULT NULL,
    `value` text DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bpm_user_group` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(255) DEFAULT NULL,
    `description` text DEFAULT NULL,
    `status` int DEFAULT NULL,
    `user_ids` text DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bpm_oa_leave` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `user_id` bigint DEFAULT NULL,
    `type` int DEFAULT NULL,
    `reason` text DEFAULT NULL,
    `start_time` datetime DEFAULT NULL,
    `end_time` datetime DEFAULT NULL,
    `day` bigint DEFAULT NULL,
    `status` int DEFAULT NULL,
    `process_instance_id` varchar(64) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_process_instance_id` (`tenant_id`, `process_instance_id`),
    KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bpm_process_instance_copy` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `start_user_id` bigint DEFAULT NULL,
    `process_instance_name` varchar(255) DEFAULT NULL,
    `process_instance_id` varchar(64) DEFAULT NULL,
    `process_definition_id` varchar(64) DEFAULT NULL,
    `category` varchar(64) DEFAULT NULL,
    `activity_id` varchar(64) DEFAULT NULL,
    `activity_name` varchar(255) DEFAULT NULL,
    `task_id` varchar(64) DEFAULT NULL,
    `user_id` bigint DEFAULT NULL,
    `reason` text DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
    KEY `idx_process_instance_id` (`tenant_id`, `process_instance_id`),
    KEY `idx_process_definition_id` (`tenant_id`, `process_definition_id`),
    KEY `idx_user_id` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
