#!/usr/bin/env python3
"""Real browser identity workflow, permissions, mapped CSV and unmodified screenshots."""
import argparse,json,os,re,time
from datetime import date as calendar_date,timedelta
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--base-url',default='http://127.0.0.1:3000')
parser.add_argument('--fixture-file',type=Path,required=True)
parser.add_argument('--output-dir',type=Path,required=True)
parser.add_argument('--chromium-bin',default='/usr/bin/chromium')
parser.add_argument('--allow-test-fixtures',action='store_true',required=True)
args=parser.parse_args();args.output_dir.mkdir(parents=True,exist_ok=True)
for role in ['', 'MAPPING_READER_', 'MAPPING_DEPT_']:
 for suffix in ['TOKEN','REFRESH_TOKEN']:
  name='HRM_'+('SMOKE_TOKEN' if not role and suffix=='TOKEN' else 'REFRESH_TOKEN' if not role else role+suffix)
  if not os.environ.get(name):parser.error('Missing verification credential: '+name)
fixture=json.loads(args.fixture_file.read_text());checks=[];base=args.base_url.rstrip('/');route=base+'/hrm/payroll-identity'
def passed(name):checks.append({'check':name,'result':'PASS'});print('PASS:',name,flush=True)
def seed(context,token='HRM_SMOKE_TOKEN',refresh='HRM_REFRESH_TOKEN'):
 values={'ACCESS_TOKEN':os.environ[token],'REFRESH_TOKEN':os.environ[refresh],'TenantId':1}
 context.add_init_script('(function(values){for(const [k,v]of Object.entries(values))localStorage.setItem(k,JSON.stringify({c:Date.now(),e:Date.now()+86400000,v:JSON.stringify(v)}));})('+json.dumps(values)+');')
def result(response):
 data=response.value.json();assert data.get('code')==0,('request failed',data.get('code'));return data['data']
def open_page(page):
 with page.expect_response(lambda r:'/payroll/identity/page' in r.url) as response:page.goto(route,wait_until='domcontentloaded')
 result(response);expect(page.get_by_role('heading',name='薪酬人员编号映射',exact=True)).to_be_visible(timeout=30000)
 expect(page.locator('.el-loading-mask:visible')).to_have_count(0)
def search(page,code):
 page.get_by_placeholder('外部编号（精确）',exact=True).fill(code)
 with page.expect_response(lambda r:'/payroll/identity/page' in r.url and 'externalCode='+code in r.url) as response:page.get_by_role('button',name='查询',exact=True).click()
 return result(response)
def row_for(page,code,version):
 return page.locator('[data-testid="identity-table"]').get_by_role('row').filter(has=page.get_by_role('cell',name=code,exact=True)).filter(has=page.get_by_role('cell',name=re.compile(r'^V'+str(version)+r'\s*·')))
def screenshot(page,name):
 expect(page.locator('.el-loading-mask:visible')).to_have_count(0,timeout=15000)
 expect(page.locator('.el-notification:visible')).to_have_count(0,timeout=10000)
 page.screenshot(path=str(args.output_dir/name),full_page=True,animations='disabled')
def date(dialog,label,value):
 field=dialog.get_by_label(label,exact=True);field.fill(value);field.press('Enter');dialog.get_by_text('请核对目标 HRM 人员。保存会刷新人员快照；确认前主档若再次变化，服务端会要求重新核对。',exact=True).click()
def check_person(page,dialog,id):
 dialog.get_by_label('HRM 人员 ID *',exact=True).fill(str(id));dialog.get_by_label('HRM 人员 ID *',exact=True).press('Tab')
 with page.expect_response(lambda r:'/payroll/identity/employee?' in r.url) as response:dialog.get_by_role('button',name='核对 HRM 人员',exact=True).click()
 result(response);expect(dialog.locator('[data-testid="selected-person"]')).to_be_visible()
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=args.chromium_bin,headless=True,args=['--no-sandbox'])
 context=browser.new_context(viewport={'width':1680,'height':1200},locale='zh-CN',timezone_id='Asia/Shanghai');seed(context)
 page=context.new_page();errors=[];page.on('pageerror',lambda e:errors.append(e.name));open_page(page)
 data=search(page,fixture['externalCode']);assert data['total']>=4
 row=row_for(page,fixture['externalCode'],fixture['mappingVersion']);expect(row.get_by_text('已确认',exact=True)).to_be_visible()
 passed('identity route shows real source exact external code version status and captured person')
 screenshot(page,'payroll-identity-desktop.png')
 row.get_by_role('button',name='详情',exact=True).click();drawer=page.locator('.el-drawer:visible')
 expect(drawer.get_by_text('编号映射合成员工 B · HRM #930000002',exact=True)).to_be_visible()
 expect(drawer.get_by_role('heading',name='主档抓取快照',exact=True)).to_be_visible()
 expect(drawer.get_by_role('heading',name='评审历史',exact=True)).to_be_visible()
 captured=drawer.get_by_role('row').filter(has=page.get_by_role('cell',name='主档抓取时间',exact=True))
 expect(captured).to_contain_text(re.compile(r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}'))
 passed('detail exposes retained minimal snapshot ISO capture time and original audit')
 screenshot(page,'payroll-identity-snapshot.png');drawer.get_by_role('button',name='关闭此对话框',exact=True).click()
 page.get_by_role('button',name='登记映射',exact=True).click();dialog=page.get_by_role('dialog').filter(has=page.get_by_text('登记人员编号映射',exact=True))
 dialog.get_by_role('button',name='保存草稿',exact=True).click();expect(dialog.get_by_text('请填写来源、命名空间、外部编号，并核对 HRM 人员。',exact=True)).to_be_visible()
 dialog.locator('.el-form-item').filter(has=page.get_by_text('数据来源 *',exact=True)).locator('.el-select').click();page.get_by_role('option',name=re.compile(r'^DS-01 ·')).click()
 ui_code='UI-MAPPING-'+str(int(time.time()));dialog.get_by_label('编号命名空间 *',exact=True).fill('QA-MAPPING');dialog.get_by_label('外部人员编号 *',exact=True).fill(ui_code)
 check_person(page,dialog,fixture['employeeA']);expect(dialog.locator('[data-testid="selected-person"]')).to_contain_text('QA-MAP-DUP')
 dialog.get_by_label('映射负责人（确认必填）',exact=True).fill('前端回归合成负责人');dialog.get_by_label('来源或核对依据（确认必填）',exact=True).fill('仅隔离 QA 示例，不代表业务核定')
 date(dialog,'生效开始（确认必填）','2026-10-01');date(dialog,'生效结束（可选）','2026-10-31')
 with page.expect_response(lambda r:'/payroll/identity/create' in r.url) as response:dialog.get_by_role('button',name='保存草稿',exact=True).click()
 ui_id=result(response);expect(dialog).not_to_be_visible();search(page,ui_code)
 passed('registration requires explicit person verification and persists a server-created draft')
 row=row_for(page,ui_code,1);row.get_by_role('button',name='确认',exact=True).click();review=page.get_by_role('dialog').filter(has=page.get_by_text('确认人员编号映射',exact=True))
 review.get_by_role('button',name='提交评审',exact=True).click();expect(review.get_by_text('请填写评审依据。',exact=True)).to_be_visible()
 review.get_by_label('评审依据 *',exact=True).fill('前端隔离回归：核对合成编号、明确有效期和人员')
 with page.expect_response(lambda r:'/payroll/identity/review' in r.url) as response:review.get_by_role('button',name='提交评审',exact=True).click()
 result(response);expect(review).not_to_be_visible();expect(row.get_by_role('button',name='编辑',exact=True)).to_have_count(0)
 passed('confirmation requires evidence and confirmed mapping locks edits')
 search(page,fixture['externalCode']);row=row_for(page,fixture['externalCode'],fixture['mappingVersion'])
 with page.expect_response(lambda r:'/payroll/identity/get?' in r.url) as version_response:
  with page.expect_response(lambda r:'/payroll/identity/new-version' in r.url) as response:row.get_by_role('button',name='另建版本',exact=True).click()
 version_id=result(response);ui_version=result(version_response)['mappingVersion'];dialog=page.get_by_role('dialog').filter(has=page.get_by_text('维护映射草稿',exact=True));expect(dialog).to_be_visible()
 expect(dialog.get_by_label('外部人员编号 *',exact=True)).to_be_disabled();check_person(page,dialog,fixture['employeeA'])
 with page.expect_response(lambda r:'/payroll/identity/update' in r.url) as response:dialog.get_by_role('button',name='保存草稿',exact=True).click()
 result(response);expect(dialog).not_to_be_visible();next_row=row_for(page,fixture['externalCode'],ui_version)
 passed('new version preserves immutable identity but explicitly rechecks another target person')
 next_row.get_by_role('button',name='确认',exact=True).click();review=page.get_by_role('dialog').filter(has=page.get_by_text('确认人员编号映射',exact=True));review.get_by_label('评审依据 *',exact=True).fill('前端隔离回归：验证期间重叠被阻断')
 with page.expect_response(lambda r:'/payroll/identity/review' in r.url) as response:review.get_by_role('button',name='提交评审',exact=True).click()
 assert response.value.json()['code']==1050940005
 expect(page.get_by_text('该编号存在有效期重叠的已确认映射',exact=True)).to_be_visible()
 passed('overlapping confirmation is rejected in the real browser')
 review.get_by_role('button',name='取消',exact=True).click();next_row.get_by_role('button',name='编辑',exact=True).click();dialog=page.get_by_role('dialog').filter(has=page.get_by_text('维护映射草稿',exact=True))
 # Each repeated isolated browser run gets its own synthetic month, without changing October's fixture.
 ui_start=calendar_date(2030+ui_version//12,ui_version%12+1,1);ui_end=(ui_start+timedelta(days=32)).replace(day=1)-timedelta(days=1);ui_day=ui_start.replace(day=15).isoformat()
 # Clear the previous end before moving the start beyond it.
 dialog.get_by_label('生效结束（可选）',exact=True).fill('');dialog.get_by_label('生效结束（可选）',exact=True).press('Tab')
 date(dialog,'生效开始（确认必填）',ui_start.isoformat());date(dialog,'生效结束（可选）',ui_end.isoformat());check_person(page,dialog,fixture['employeeA'])
 with page.expect_response(lambda r:'/payroll/identity/update' in r.url) as response:dialog.get_by_role('button',name='保存草稿',exact=True).click()
 result(response);expect(dialog).not_to_be_visible();next_row.get_by_role('button',name='确认',exact=True).click();review=page.get_by_role('dialog').filter(has=page.get_by_text('确认人员编号映射',exact=True));review.get_by_label('评审依据 *',exact=True).fill('前端隔离回归：下一期间合成版本')
 with page.expect_response(lambda r:'/payroll/identity/review' in r.url) as response:review.get_by_role('button',name='提交评审',exact=True).click()
 result(response);expect(review).not_to_be_visible();expect(next_row.get_by_text('已确认',exact=True)).to_be_visible()
 passed('nonoverlapping version confirms without changing the earlier reviewed period')
 page.locator('.lookup-grid .el-form-item').filter(has=page.get_by_text('核对来源',exact=True)).locator('.el-select').click();page.get_by_role('option',name=re.compile(r'^DS-01 ·')).click()
 page.get_by_label('核对命名空间',exact=True).fill(fixture['namespace']);page.get_by_label('核对外部编号',exact=True).fill(fixture['externalCode'])
 for label in ['核对开始日期','核对结束日期']:
  field=page.get_by_label(label,exact=True);field.fill(ui_day);field.press('Enter')
 page.get_by_role('heading',name='按外部编号和期间核对',exact=True).click()
 with page.expect_response(lambda r:'/payroll/identity/resolve' in r.url) as response:page.get_by_role('button',name='核对编号',exact=True).click()
 match=result(response);assert match['mappingId']==version_id and match['employeeId']==fixture['employeeA']
 expect(page.locator('[data-testid="identity-match"]')).to_contain_text('V'+str(ui_version))
 screenshot(page,'payroll-identity-period-lookup.png');passed('manual period lookup resolves the actual newer version and captured time')
 page.goto(base+'/hrm/payroll-intake',wait_until='domcontentloaded');expect(page.get_by_role('heading',name='薪酬数据接入准备',exact=True)).to_be_visible(timeout=15000)
 page.get_by_placeholder('搜索契约名称或来源编号').fill(fixture['contractTitle'])
 with page.expect_response(lambda r:'/intake/contracts/page' in r.url) as response:page.get_by_role('button',name='查询',exact=True).click()
 contracts=result(response)['list'];selected=next(c for c in contracts if c['id']==fixture['contractId'])
 contract_row=page.locator('[data-testid="contracts-table"]').get_by_role('row').filter(has=page.get_by_text(fixture['contractTitle'],exact=True)).filter(has=page.get_by_role('cell',name='V'+str(selected['contractVersion']),exact=True))
 contract_row.get_by_role('button',name='详情',exact=True).click();drawer=page.locator('.el-drawer:visible');expect(drawer).to_contain_text('外部编号 external / QA-MAPPING')
 drawer.get_by_role('button',name='关闭此对话框',exact=True).click();contract_row.get_by_role('button',name='预检',exact=True).click()
 expect(page.get_by_text(re.compile(r'人员核对：按外部编号字段 external'))).to_be_visible()
 page.get_by_placeholder('由提交人核实并填写').fill('隔离 QA 演示范围');page.get_by_placeholder('开始日期').fill(fixture['periodStart']);page.get_by_placeholder('结束日期').fill(fixture['periodEnd']);page.get_by_placeholder('结束日期').press('Enter');page.get_by_role('heading',name='薪酬数据接入准备',exact=True).click()
 page.locator('input[type="file"]').set_input_files(str(args.fixture_file.parent/'mapping-preview.csv'))
 with page.expect_response(lambda r:'/intake/batches/preview' in r.url) as response:page.get_by_role('button',name='上传并预检',exact=True).click()
 id=result(response);assert id==fixture['batchId'];display=page.locator('[data-testid="batch-result"]').filter(visible=True)
 expect(display).to_contain_text('映射 #'+str(fixture['mappingId'])+' · V'+str(fixture['mappingVersion']))
 expect(display.get_by_text('(UNRESOLVED_MAPPING)',exact=True)).to_be_visible();expect(display).to_contain_text('计薪资格、来源完整性和薪酬规则仍需确认')
 display.scroll_into_view_if_needed();screenshot(page,'payroll-identity-csv-precheck.png')
 passed('actual CSV upload reuses its frozen batch and shows mapped version with unresolved row errors')
 display.locator('.el-switch').click();expect(display.get_by_text(fixture['externalCode'],exact=True)).to_have_count(0)
 passed('mapped CSV problem filter excludes the valid mapped row')
 reader=browser.new_context(viewport={'width':1440,'height':1000},locale='zh-CN');seed(reader,'HRM_MAPPING_READER_TOKEN','HRM_MAPPING_READER_REFRESH_TOKEN');rp=reader.new_page();open_page(rp);search(rp,fixture['externalCode'])
 for name in ['登记映射','编辑','确认','停用','另建版本']:expect(rp.get_by_role('button',name=name,exact=True)).to_have_count(0)
 expect(row_for(rp,fixture['externalCode'],fixture['mappingVersion']).get_by_role('button',name='详情',exact=True)).to_be_visible()
 passed('read-only identity permits details and lookup without maintenance or review controls');reader.close()
 scoped=browser.new_context(viewport={'width':1440,'height':1000},locale='zh-CN');seed(scoped,'HRM_MAPPING_DEPT_TOKEN','HRM_MAPPING_DEPT_REFRESH_TOKEN');sp=scoped.new_page();open_page(sp);data=search(sp,fixture['externalCode']);assert all(r['employeeId']==fixture['employeeA'] for r in data['list'])
 expect(sp.locator('[data-testid="identity-table"]').get_by_text('编号映射合成员工 B',exact=True)).to_have_count(0)
 row_for(sp,fixture['externalCode'],ui_version).get_by_role('button',name='详情',exact=True).click();drawer=sp.locator('.el-drawer:visible');drawer.locator('.el-collapse-item__header').first.click()
 expect(drawer.get_by_text('历史快照按人员范围隐藏',exact=True).first).to_be_visible();expect(drawer.locator('pre')).to_have_count(0)
 screenshot(sp,'payroll-identity-scoped-history.png');passed('department UI excludes other persons and hides every historical personal snapshot');scoped.close()
 mobile=browser.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True,locale='zh-CN');seed(mobile);mp=mobile.new_page();open_page(mp);search(mp,fixture['externalCode'])
 assert mp.evaluate('document.documentElement.scrollWidth<=window.innerWidth');screenshot(mp,'payroll-identity-mobile.png')
 mp.get_by_role('button',name='登记映射',exact=True).click();dialog=mp.get_by_role('dialog').filter(has=mp.get_by_text('登记人员编号映射',exact=True));expect(dialog).to_be_visible();assert mp.evaluate('document.documentElement.scrollWidth<=window.innerWidth');dialog.get_by_role('button',name='取消',exact=True).click()
 passed('390px mobile contains horizontal table scrolling and stacks registration fields');mobile.close()
 assert not errors,errors;passed('no uncaught browser page errors')
 context.close();browser.close()
(args.output_dir/'hrm-identity-ui-results.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2))
print('All',len(checks),'identity browser checks passed')
