#!/usr/bin/env python3
"""Live ledger UI regression and unmodified screenshots; only for an isolated verification database."""
import argparse,json,os
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--base-url',default='http://127.0.0.1:3000')
parser.add_argument('--fixture-file',type=Path,required=True)
parser.add_argument('--output-dir',type=Path,required=True)
parser.add_argument('--chromium-bin',default='/usr/bin/chromium')
parser.add_argument('--allow-test-fixtures',action='store_true',required=True)
args=parser.parse_args();args.output_dir.mkdir(parents=True,exist_ok=True)
for name in ['HRM_SMOKE_TOKEN','HRM_REFRESH_TOKEN','HRM_READER_TOKEN','HRM_READER_REFRESH_TOKEN']:
 if not os.environ.get(name):parser.error('Missing verification credential: '+name)
fixture=json.loads(args.fixture_file.read_text());checks=[];base=args.base_url.rstrip('/')
def passed(name):checks.append({'check':name,'result':'PASS'});print('PASS:',name,flush=True)
def seed(context,token,refresh):
 values={'ACCESS_TOKEN':os.environ[token],'REFRESH_TOKEN':os.environ[refresh],'TenantId':1}
 context.add_init_script('const values='+json.dumps(values)+';for(const[k,v]of Object.entries(values))localStorage.setItem(k,JSON.stringify({c:Date.now(),e:Date.now()+86400000,v:JSON.stringify(v)}));')
def result(response):
 r=response.value.json();assert r.get('code')==0,('request failed',r.get('code'));return r.get('data')
def row_for(page,version):
 return page.locator('[data-testid="rule-table"]').get_by_role('row').filter(has=page.get_by_text(fixture['code'],exact=True)).filter(has=page.get_by_role('cell',name='V'+str(version),exact=True))
def screenshot(page,name):
 expect(page.locator('.el-loading-mask:visible')).to_have_count(0,timeout=15000)
 expect(page.locator('.el-notification:visible')).to_have_count(0,timeout=10000)
 page.screenshot(path=str(args.output_dir/name),full_page=True,animations='disabled')
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=args.chromium_bin,headless=True,args=['--no-sandbox'])
 context=browser.new_context(viewport={'width':1680,'height':1250},locale='zh-CN',timezone_id='Asia/Shanghai')
 seed(context,'HRM_SMOKE_TOKEN','HRM_REFRESH_TOKEN');page=context.new_page();errors=[]
 page.on('pageerror',lambda e:errors.append(e.name))
 page.goto(base+'/hrm/payroll-rules',wait_until='domcontentloaded')
 expect(page.get_by_role('heading',name='薪酬规则台账',exact=True)).to_be_visible(timeout=30000)
 page.get_by_placeholder('搜索规则编号或名称').fill(fixture['code'])
 with page.expect_response(lambda r:'/payroll/rules/page' in r.url) as response:page.get_by_role('button',name='查询',exact=True).click()
 result(response);expect(row_for(page,2)).to_be_visible()
 passed('ledger route renders real API versions statuses and ISO dates')
 screenshot(page,'payroll-rules-desktop.png')
 row_for(page,2).get_by_role('button',name='详情',exact=True).click();drawer=page.locator('.el-drawer:visible')
 expect(drawer.get_by_role('heading',name='业务输入与预期样例',exact=True)).to_be_visible()
 expect(drawer.get_by_text('零值保留 0；缺失不得推定为零。仅用于验证资料登记，不代表实际金额计算。',exact=True)).to_be_visible()
 expect(drawer.get_by_role('cell',name='0 演示单位',exact=True)).to_be_visible()
 expect(drawer.get_by_role('cell',name='false',exact=True)).to_be_visible()
 expect(drawer.get_by_role('heading',name='评审历史',exact=True)).to_be_visible()
 passed('detail displays canonical zero false business evidence and audit history')
 screenshot(page,'payroll-rules-detail.png');drawer.get_by_role('button',name='关闭此对话框',exact=True).click()
 with page.expect_response(lambda r:'/payroll/rules/new-version' in r.url) as response:row_for(page,2).get_by_role('button',name='另建版本',exact=True).click()
 ui_id=result(response)
 dialog=page.get_by_role('dialog').filter(has=page.get_by_text('维护规则草稿',exact=True));expect(dialog).to_be_visible()
 expected='前端回归预期：零值保持 0；仅登记合成样例，不执行正式计算。'
 dialog.get_by_label('规则名称 *',exact=True).fill(fixture['title']+' · 页面版本')
 dialog.get_by_label('业务确认的预期结果 *',exact=True).fill(expected)
 with page.expect_response(lambda r:'/payroll/rules/update' in r.url) as response:dialog.get_by_role('button',name='保存草稿',exact=True).click()
 result(response);expect(dialog).not_to_be_visible()
 # Versions 3/4 were allocated by API concurrency regression; the UI version follows them.
 row=page.locator('[data-testid="rule-table"]').get_by_role('row').filter(has=page.get_by_text(fixture['title']+' · 页面版本',exact=True))
 expect(row).to_be_visible();passed('new version copies reviewed inputs as draft and UI edits persist')
 row.get_by_role('button',name='确认',exact=True).click()
 review_dialog=page.get_by_role('dialog').filter(has=page.get_by_text('确认业务口径',exact=True))
 review_dialog.get_by_role('button',name='提交评审',exact=True).click()
 expect(review_dialog.get_by_text('请填写评审依据。',exact=True)).to_be_visible()
 review_dialog.get_by_label('评审依据 *',exact=True).fill('页面回归：先验证重叠阻断，再调整适用期间')
 with page.expect_response(lambda r:'/payroll/rules/review' in r.url) as response:review_dialog.get_by_role('button',name='提交评审',exact=True).click()
 assert response.value.json()['code']==1050930005
 expect(page.get_by_text('同编号、同范围已有生效期间重叠的确认版本',exact=True)).to_be_visible()
 passed('confirmation requires evidence and interval overlap remains blocked in browser')
 review_dialog.get_by_role('button',name='取消',exact=True).click();row.get_by_role('button',name='编辑',exact=True).click()
 dialog=page.get_by_role('dialog').filter(has=page.get_by_text('维护规则草稿',exact=True))
 dialog.get_by_label('范围编号（确认必填）',exact=True).fill('QA-UI-ONLY')
 with page.expect_response(lambda r:'/payroll/rules/update' in r.url) as response:dialog.get_by_role('button',name='保存草稿',exact=True).click()
 result(response);expect(dialog).not_to_be_visible();row.get_by_role('button',name='确认',exact=True).click()
 review_dialog=page.get_by_role('dialog').filter(has=page.get_by_text('确认业务口径',exact=True))
 review_dialog.get_by_label('评审依据 *',exact=True).fill('页面回归：隔离样例范围确认，非生产制度')
 with page.expect_response(lambda r:'/payroll/rules/review' in r.url) as response:review_dialog.get_by_role('button',name='提交评审',exact=True).click()
 result(response);expect(review_dialog).not_to_be_visible();expect(row.get_by_role('button',name='编辑',exact=True)).to_have_count(0)
 passed('reviewed nonoverlapping scope locks edits after successful confirmation')
 row.get_by_role('button',name='详情',exact=True).click();drawer=page.locator('.el-drawer:visible')
 expect(drawer.get_by_text(expected,exact=True)).to_be_visible()
 passed('saved expected example reloads from frozen reviewed version')
 screenshot(page,'payroll-rules-reviewed-example.png');drawer.get_by_role('button',name='关闭此对话框',exact=True).click()
 row.get_by_role('button',name='停用',exact=True).click();retire=page.get_by_role('dialog').filter(has=page.get_by_text('停用业务口径',exact=True))
 retire.get_by_label('评审依据 *',exact=True).fill('页面回归：停用演示版本并保留评审记录')
 with page.expect_response(lambda r:'/payroll/rules/review' in r.url) as response:retire.get_by_role('button',name='提交评审',exact=True).click()
 result(response);expect(retire).not_to_be_visible();expect(row.get_by_text('已停用',exact=True)).to_be_visible()
 row.get_by_role('button',name='详情',exact=True).click();drawer=page.locator('.el-drawer:visible');expect(drawer.get_by_text(expected,exact=True)).to_be_visible()
 passed('retired rule preserves original parameters examples and audit')
 drawer.get_by_role('button',name='关闭此对话框',exact=True).click()
 reader=browser.new_context(viewport={'width':1440,'height':1000},locale='zh-CN');seed(reader,'HRM_READER_TOKEN','HRM_READER_REFRESH_TOKEN')
 rp=reader.new_page();rp.goto(base+'/hrm/payroll-rules',wait_until='domcontentloaded');expect(rp.get_by_role('heading',name='薪酬规则台账',exact=True)).to_be_visible(timeout=30000)
 for name in ['登记待决口径','补充规则','编辑','确认','停用','另建版本']:expect(rp.get_by_role('button',name=name,exact=True)).to_have_count(0)
 passed('reader sees ledger metadata without mutation buttons');reader.close()
 mobile=browser.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True,locale='zh-CN');seed(mobile,'HRM_SMOKE_TOKEN','HRM_REFRESH_TOKEN')
 mp=mobile.new_page();mp.goto(base+'/hrm/payroll-rules',wait_until='domcontentloaded');expect(mp.get_by_role('heading',name='薪酬规则台账',exact=True)).to_be_visible(timeout=30000)
 assert mp.evaluate('document.documentElement.scrollWidth<=window.innerWidth');screenshot(mp,'payroll-rules-mobile.png')
 mp.get_by_role('button',name='补充规则',exact=True).click();md=mp.get_by_role('dialog').filter(has=mp.get_by_text('补充业务规则',exact=True));expect(md).to_be_visible()
 expect(md.get_by_label('规则编号 *',exact=True)).to_be_visible();assert mp.evaluate('document.documentElement.scrollWidth<=window.innerWidth')
 screenshot(mp,'payroll-rules-mobile-form.png');passed('mobile ledger and rule form fit a 390px viewport');mobile.close()
 assert not errors,'Browser runtime errors: '+','.join(errors);passed('no uncaught browser page errors')
 context.close();browser.close()
(args.output_dir/'hrm-rule-ui-results.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2))
(args.output_dir/'hrm-rule-ui-fixture.json').write_text(json.dumps({'uiRuleId':ui_id},ensure_ascii=False))
print('All',len(checks),'rule browser regression checks passed')
