#!/usr/bin/env python3
"""Browser regression and screenshots; writes fixtures in an isolated verification database."""
from pathlib import Path
import argparse, json, os, zipfile, xml.etree.ElementTree as E
from playwright.sync_api import sync_playwright,expect
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--base-url', default='http://127.0.0.1:3000')
parser.add_argument('--output-dir', type=Path, required=True)
parser.add_argument('--fixture-file', type=Path, required=True, help='Fixture JSON generated by verify-collection-api.py')
parser.add_argument('--chromium-bin', default='/usr/bin/chromium')
parser.add_argument('--allow-test-fixtures', action='store_true', required=True)
args=parser.parse_args()
root=args.output_dir;root.mkdir(parents=True,exist_ok=True)
base=args.base_url.rstrip('/')
required=['HRM_SMOKE_TOKEN','HRM_REFRESH_TOKEN','HRM_READER_TOKEN','HRM_READER_REFRESH_TOKEN']
for name in required:
 if not os.environ.get(name):parser.error('Missing verification credential: '+name)
auth={'accessToken':os.environ['HRM_SMOKE_TOKEN'],'refreshToken':os.environ['HRM_REFRESH_TOKEN']}
reader_auth={'accessToken':os.environ['HRM_READER_TOKEN'],'refreshToken':os.environ['HRM_READER_REFRESH_TOKEN']}
fixture=json.loads(args.fixture_file.read_text())
checks=[]
def passed(name):checks.append({'check':name,'result':'PASS'});print('PASS:',name,flush=True)
def seed(context,credential):
 values={'ACCESS_TOKEN':credential['accessToken'],'REFRESH_TOKEN':credential['refreshToken'],'TenantId':1}
 context.add_init_script('const values = '+json.dumps(values)+'; for (const [key,value] of Object.entries(values)) localStorage.setItem(key,JSON.stringify({c:Date.now(),e:Date.now()+86400000,v:JSON.stringify(value)}));')
def expect_success(promise):
 result=promise.value.json()
 assert result['code']==0,result
 return result.get('data')
def row_for(page,code):return page.get_by_role('row').filter(has=page.get_by_text(code,exact=True))
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=args.chromium_bin,headless=True,args=['--no-sandbox'])
 context=browser.new_context(viewport={'width':1680,'height':1050},locale='zh-CN',timezone_id='Asia/Shanghai')
 seed(context,auth)
 page=context.new_page();errors=[]
 page.on('pageerror',lambda e:errors.append(e.name))
 page.goto(base+'/hrm/payroll-requirements',wait_until='domcontentloaded')
 expect(page.get_by_role('heading',name='薪酬需求征集')).to_be_visible(timeout=30000)
 expect(page.get_by_role('cell',name='OV-01',exact=True)).to_be_visible()
 passed('authenticated collection page loads with real API data')
 page.get_by_role('button',name='需求征集',exact=True).click()
 row=row_for(page,fixture['customCode']);expect(row).to_be_visible()
 row.get_by_role('button',name='维护',exact=True).click()
 dialog=page.get_by_role('dialog').filter(has=page.get_by_text('维护需求 · '+fixture['customCode'],exact=True))
 expect(dialog).to_be_visible()
 dialog.get_by_label('需求负责人',exact=True).fill('前端回归负责人（演示）')
 dialog.get_by_label('验收条件',exact=True).fill('前端回归：保存后重载可读取，评审记录完整，旧基线可重复下载。')
 dialog.get_by_label('备注与未决问题',exact=True).fill('仅为隔离测试样例；真实核算范围、工资周期及政策依据待业务确认。')
 with page.expect_response(lambda r:r.url.endswith('/requirements/update') and r.request.method=='PUT') as response:
  dialog.get_by_role('button',name='保存需求').click()
 expect_success(response);expect(dialog).not_to_be_visible()
 page.reload(wait_until='domcontentloaded')
 row=row_for(page,fixture['customCode']);expect(row.get_by_role('cell',name='前端回归负责人（演示）')).to_be_visible()
 passed('form saves and persisted owner survives a full browser reload')
 row.get_by_role('button',name='评审',exact=True).click()
 dialog=page.get_by_role('dialog').filter(has=page.get_by_text('评审需求 · '+fixture['customCode'],exact=True))
 dialog.locator('label.el-radio').filter(has_text='已确认').click()
 expect(dialog.get_by_role('radio',name='已确认',exact=True)).to_be_checked()
 dialog.get_by_label('评审依据 / 未决问题',exact=True).fill('前端回归：依据实际保存、重载与版本记录核验确认（演示记录）。')
 with page.expect_response(lambda r:r.url.endswith('/requirements/review') and r.request.method=='POST') as response:
  dialog.get_by_role('button',name='提交评审').click()
 expect_success(response);expect(dialog).not_to_be_visible()
 expect(row.get_by_text('已确认',exact=True)).to_be_visible()
 passed('review through UI persists confirmation')
 page.screenshot(path=str(root/'payroll-requirements-desktop.png'),full_page=True)
 row.get_by_role('button',name='记录',exact=True).click()
 drawer=page.locator('.el-drawer:visible')
 expect(drawer.locator('.el-timeline-item p').filter(has_text='前端回归：依据实际保存').first).to_be_visible()
 expect(drawer.locator('.el-loading-mask:visible')).to_have_count(0)
 page.screenshot(path=str(root/'payroll-review-history.png'),full_page=True)
 passed('history shows actual actor, timestamp, basis and previous versions')
 drawer.get_by_role('button',name='关闭此对话框',exact=True).click()
 page.get_by_role('tab',name='数据来源',exact=True).click()
 source=row_for(page,'DS-02');source.get_by_role('button',name='维护',exact=True).click()
 dialog=page.get_by_role('dialog').filter(has=page.get_by_text('数据来源 · DS-02',exact=True))
 dialog.locator('label.el-radio').filter(has_text='待补齐').click()
 expect(dialog.get_by_role('radio',name='待补齐',exact=True)).to_be_checked()
 dialog.get_by_label('核验依据 / 数据缺口',exact=True).fill('回归样例：实际考勤系统的字段契约尚未提供，需由业务负责人补齐。')
 with page.expect_response(lambda r:r.url.endswith('/sources/update') and r.request.method=='PUT') as response:
  dialog.get_by_role('button',name='保存来源').click()
 expect_success(response);expect(dialog).not_to_be_visible()
 expect(source.get_by_text('待补齐',exact=True)).to_be_visible()
 passed('source gap can be maintained independently of confirmed functions')
 page.screenshot(path=str(root/'payroll-data-sources.png'),full_page=True)
 row_for(page,'DS-01').get_by_role('button',name='关联需求',exact=True).click()
 tag=page.locator('.source-filter');expect(tag).to_contain_text('DS-01')
 expect(page.get_by_role('cell',name='CALC-01',exact=True)).to_be_visible()
 tag.locator('.el-tag__close').click();expect(tag).to_have_count(0)
 expect(page.get_by_role('cell',name='OV-01',exact=True)).to_be_visible()
 page.get_by_role('button',name='需求征集',exact=True).click()
 expect(row_for(page,fixture['customCode'])).to_be_visible()
 passed('source link filters real requirements; closing the filter restores the full query')
 page.get_by_role('tab',name='评审基线',exact=True).click()
 page.get_by_role('button',name='生成评审基线',exact=True).click()
 with page.expect_response(lambda r:r.url.endswith('/baselines/create') and r.request.method=='POST') as response:
  page.locator('.el-message-box').get_by_role('button',name='确定',exact=True).click()
 new_baseline=expect_success(response)
 expect(row_for(page,'B'+str(new_baseline))).to_be_visible()
 old_row=row_for(page,'B'+str(fixture['baseline']))
 with page.expect_download() as downloaded:
  old_row.get_by_role('button',name='下载 Excel').click()
 download=downloaded.value;target=root/'payroll-review-old-baseline.xlsx';download.save_as(str(target))
 ns={'s':'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
 with zipfile.ZipFile(target) as z:
  text=[t.text for t in E.fromstring(z.read('xl/worksheets/sheet1.xml')).findall('.//s:t',ns)]
  assert '回归样例：需求评审与版本核验' in text
  assert '前端回归负责人（演示）' not in text
 passed('UI creates a baseline and downloads an old immutable Excel snapshot')
 page.screenshot(path=str(root/'payroll-review-baselines.png'),full_page=True)
 # Exercise the inline error state and recovery using an actual failed API response.
 page.route('**/hrm/payroll/requirements/page?*',lambda route:route.fulfill(status=200,content_type='application/json',body='{"code":500,"msg":"回归模拟读取失败"}'))
 page.get_by_role('tab',name='功能需求',exact=True).click()
 page.get_by_role('button',name='查询',exact=True).click()
 expect(page.get_by_text('需求加载失败，请重试。',exact=True)).to_be_visible()
 page.unroute('**/hrm/payroll/requirements/page?*')
 page.get_by_role('button',name='重新加载',exact=True).click()
 expect(row_for(page,fixture['customCode'])).to_be_visible()
 passed('failed query renders a clear error and retry restores persisted data')
 assert not errors,errors
 # Screenshot the already completed foundation module's actual authenticated HRM page.
 page.goto(base+'/hrm/employee/list',wait_until='domcontentloaded')
 expect(page.get_by_role('button',name='新增',exact=True)).to_be_visible(timeout=20000)
 expect(page.locator('.el-loading-mask:visible')).to_have_count(0)
 page.screenshot(path=str(root/'hrm-foundation-employee-page.png'),full_page=True)
 passed('foundation HRM employee page remains available after collection integration')
 mobile=browser.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True,device_scale_factor=1,locale='zh-CN',timezone_id='Asia/Shanghai')
 seed(mobile,auth);mp=mobile.new_page()
 mp.goto(base+'/hrm/payroll-requirements?module=req',wait_until='domcontentloaded')
 expect(mp.get_by_role('heading',name='薪酬需求征集')).to_be_visible(timeout=20000)
 expect(row_for(mp,fixture['customCode'])).to_be_visible()
 mp.mouse.move(385, 5)
 mp.get_by_role('heading',name='薪酬需求征集').tap()
 expect(mp.locator('.el-menu--popup:visible')).to_have_count(0)
 assert mp.evaluate('document.documentElement.scrollWidth')<=392
 mp.screenshot(path=str(root/'payroll-requirements-mobile.png'),full_page=True)
 passed('mobile layout renders summary and module collection without page overflow')
 row_for(mp,fixture['customCode']).get_by_role('button',name='维护',exact=True).tap()
 dialog=mp.get_by_role('dialog').filter(has=mp.get_by_text('维护需求 · '+fixture['customCode'],exact=True));expect(dialog).to_be_visible()
 dialog.get_by_label('备注与未决问题',exact=True).fill('移动端输入核验，仅预览不保存。')
 assert dialog.bounding_box()['width']<=390
 mp.screenshot(path=str(root/'payroll-requirement-mobile-form.png'),full_page=True)
 dialog.get_by_role('button',name='取消',exact=True).tap()
 passed('mobile edit form accepts input within the screen width')
 reader=browser.new_context(viewport={'width':1440,'height':900},locale='zh-CN')
 seed(reader,reader_auth);rp=reader.new_page()
 rp.goto(base+'/hrm/payroll-requirements',wait_until='domcontentloaded')
 expect(rp.get_by_role('heading',name='薪酬需求征集')).to_be_visible(timeout=20000)
 expect(rp.get_by_role('cell',name='OV-01',exact=True)).to_be_visible()
 expect(rp.get_by_role('button',name='补充需求',exact=True)).to_have_count(0)
 expect(rp.get_by_role('button',name='维护',exact=True)).to_have_count(0)
 expect(rp.get_by_role('button',name='评审',exact=True)).to_have_count(0)
 rp.get_by_role('tab',name='评审基线',exact=True).click()
 expect(rp.get_by_role('button',name='生成评审基线',exact=True)).to_have_count(0)
 expect(rp.get_by_role('button',name='下载 Excel',exact=True)).to_have_count(0)
 passed('read-only role hides create, edit, review and export actions')
 browser.close()
(root/'payroll-ui-regression.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2))
print('All',len(checks),'browser checks passed')
